const TRANSPARENT_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';

const TRANSPARENT_PIXEL_BUFFER = Buffer.from(TRANSPARENT_PNG_BASE64, 'base64');

module.exports = {
  TRANSPARENT_PIXEL_BUFFER,
};
